# Makefile for make!  (Minix PC)

CFLAGS = -O -Dunix

OBJS =	check.o input.o macro.o main.o make.o reader.o rules.o

make :	$(OBJS)
	$(CC) -o make $(OBJS)
 
clean:	
	rm -f *.o *.bak make core

$(OBJS): h.h
